version: '3.4'

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
  
  cachedata:
    image: redis:alpine

  sqldata-listing:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"
    volumes:
      - sqldata-listing:/var/opt/mssql
    
  sqldata-review:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6434:1433"
    volumes:
      - sqldata-review:/var/opt/mssql
  
  sqldata-identity:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6435:1433"
    volumes:
      - sqldata-identity:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
  
  identity-api:
    image: ${REGISTRY:-burger}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata-identity;Initial Catalog=BurgerBackend.IdentityDb;User Id=sa;Password=Pass@word;Encrypt=False;
      - ReviewApiClient=http://docker.for.mac.localhost:5102
      - UseCustomizationData=True
    ports:
      - "5103:80"
    depends_on:
      - sqldata-listing

  review-api:
    image: ${REGISTRY:-burger}/review.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Review.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrlExternal=http://docker.for.mac.localhost:5103
      - IdentityUrl=http://docker.for.mac.localhost:5103
      - ConnectionString=Server=sqldata-review;Initial Catalog=BurgerBackend.ReviewDb;User Id=sa;Password=Pass@word;Encrypt=False;
      - EventBusConnection=rabbitmq
      - PATH_BASE=/review-api
    ports:
      - "5102:80"
    depends_on:
      - rabbitmq
      - sqldata-review
  
  listing-api:
    image: ${REGISTRY:-burger}/listing.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Listing.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata-listing;Initial Catalog=BurgerBackend.ListingDb;User Id=sa;Password=Pass@word;Encrypt=False;
      - RedisConnectionString=cachedata
      - EventBusConnection=rabbitmq
      - PATH_BASE=/listing-api
    ports:
      - "5101:80"
    depends_on:
      - rabbitmq
      - sqldata-identity
      - cachedata

volumes:
  sqldata-listing:
    external: false
    
  sqldata-review:
    external: false
    
  sqldata-identity:
    external: false
